### PR TITLE
Update to current Crystal

### PR DESCRIPTION
**Pull request by devnote-dev**
This PR updates the codebase to current Crystal and removes the use of internal Crystal APIs to work across different platforms. Formatting, typings and implementation details have been updated which should make the library easier to use.

### CODE REVIEW

**Comment by watzon** [comment]
Very nice. I don't have the time to verify all of this right now, but I'll merge it anyway. Do you think you could give me a list of breaking changes (if any)? I need to know how this could affect the other term libraries.

**Comment by devnote-dev** [comment]
Breaking changes:

- Renamed `CTRL_KEYS` to `CONTROL_KEYS`
- `Term::Reader#get_codes` no longer taking an array as the first parameter
- `Term::Reader#read_line` no longer accepting positional arguments, only named arguments
- `Term::Reader#clear_display` no longer has a default value for the `screen_width` parameter
- `Term::Reader#count_screen_lines` no longer has a default value for the `screen_width` parameter

There is a chance that adding type annotations to most methods could also possibly be breaking but I haven't been able to find any issues related to that.

**Comment by watzon** [comment]
Wonderful. I know it's a lot to ask, but if you have time would you mind going through the other libraries and checking for any stuff that might break because of those changes? If not no worries, I can find some time to do it later. Thanks for this!

**Comment by devnote-dev** [comment]
That was my plan, I'm working my way through all of them to get them up to date with Crystal. 😄

**Pull request merged**
